version: '3'

services:
  app:
      build:
        context: .
        dockerfile: App.Dockerfile
      ports:
        - 5000:5000
      restart: always

  nginx:
      build:
        context: .
        dockerfile: nginx.Dockerfile
      ports:
        - 80:80
      restart: always

  test:
    build:
        context: .
        dockerfile: Chrome.Dockerfile
    depends_on:
      - app
      - nginx
