#!/bin/bash


echo ""
echo "----------------------- serve experiment -------------------------"
echo ""
echo "Demonstrates that curl can access the host app on port 5000..."
echo ""
curl http://app:5000/

echo ""
echo "Demonstrates that chrome headless is working..."
echo ""

google-chrome \
--headless  \
--disable-gpu  \
--no-sandbox  \
--dump-dom \
http://example.com/

echo ""
echo "Demonstrates that chrome headless is not successful with app:500"
echo

google-chrome \
--headless  \
--disable-gpu  \
--no-sandbox  \
--dump-dom \
--enable-logging --v=10000 \
http://app:5000/

echo ""
echo "----------------------- nginx experiment -------------------------"


echo ""
echo "Will nginx curl work?"
echo
curl http://nginx/

echo ""
echo "Will nginx chrome work?"
echo
google-chrome \
--headless  \
--disable-gpu  \
--no-sandbox  \
--dump-dom \
--enable-logging --v=10000 \
http://nginx/
