#!/bin/bash

echo ""
echo "Demonstrates that curl can access the host app on port 5000..."
echo ""
curl http://app:5000/

echo ""
echo "Demonstrates that chrome headless is working..."
echo ""

google-chrome \
--headless  \
--disable-gpu  \
--no-sandbox  \
--dump-dom \
http://example.com/

echo ""
echo "Demonstrates that chrome headless is not successful with app:500"
echo

google-chrome \
--headless  \
--disable-gpu  \
--no-sandbox  \
--dump-dom \
--enable-logging --v=10000 \
http://app:5000/
